---
collections:
  - name: ansible.posix
    version: 2.1.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.docker
    version: 4.7.0
    source: https://github.com/ansible-collections/community.docker.git
    type: git
  - name: community.general
    version: 11.2.1
    source: https://github.com/ansible-collections/community.general.git
    type: git
