[tox]
minversion = 4.0.2
requires =
  tox>=4.0.2
envlist =
  devel
  docker
  docker-upstream
  upstream
skipsdist = true

[testenv]
description = Run tests using molecule ({env_name})
base_python = python3.13
set_env =
    PYTHON_LIB_PATH={envdir}/lib/{basepython}/site-packages
    ANSIBLE_REMOTE_TMP=/var/tmp/${USER}/ansible
    ANSIBLE_FILTER_PLUGINS={env:PYTHON_LIB_PATH}/molecule/provisioner/ansible/plugins/filter:${HOME}/.ansible/plugins/filter:/usr/share/ansible/plugins/filter
    ANSIBLE_LIBRARY={env:PYTHON_LIB_PATH}/molecule/provisioner/ansible/plugins/modules:${HOME}/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
deps =
    upstream: -r requirements-upstream.txt
    !upstream: -r requirements-dev.txt
commands =
    ansible --version
    ansible-lint --version
    molecule --version
    ansible-galaxy install --force -r requirements.yml
    ansible-lint
    docker: molecule test -s docker
    !docker: molecule test
