---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      debiantesting:
        docker_add_alias: true
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_user: debiantestinguser
        docker_user_bashrc: false
      bookworm:
        docker_add_alias: true
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_user: bookwormuser
        docker_user_bashrc: false
        docker_compose: false
        docker_expose_docker_api_via_tcp: true
      almalinux8:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: true
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: true
        docker_compose: false
      almalinux9:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: true
      focal:
        docker_add_alias: true
        docker_allow_ping: false
        docker_allow_privileged_ports: true
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: false
      focalroot:
        docker_add_alias: false
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: false
        docker_expose_docker_api_via_tcp: true
      jammy:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: jammyuser
        docker_user_bashrc: true
        docker_compose: true
platforms:
  - name: bookworm
    box: debian/bookworm64
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: debiantesting
    box: debian/testing64
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: almalinux8
    box: almalinux/8
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: almalinux9
    box: almalinux/9
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: false }"
      - vbguest.auto_update = false
    memory: 1024
  - name: focalroot
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: false }"
      - vbguest.auto_update = false
    memory: 1024
  - name: jammy
    box: bento/ubuntu-22.04
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: false }"
      - vbguest.auto_update = false
    memory: 1024
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
