---
- name: Prepare
  hosts: molecule
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Install Python 3
      ansible.builtin.raw: >
        DEBIAN_FRONTEND=noninteractive apt-get install --update -y python3 python3-apt || \
        dnf install -y python3 python3-dnf || microdnf install -y python3 python3-dnf
      changed_when: false

    - name: Install sudo
      ansible.builtin.raw: >
        DEBIAN_FRONTEND=noninteractive apt-get install --update -y sudo || \
        microdnf install -y sudo || dnf install -y sudo
      changed_when: false

    - name: Gather facts
      ansible.builtin.gather_facts:
