---
docker_add_alias: true
docker_allow_ping: false
docker_allow_privileged_ports: false
docker_compose: false
docker_rootful: false
docker_rootful_enabled: false
docker_user: dockeruser
docker_user_bashrc: false
